version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Prague
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: sphinx-tabs
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: sphinx-rtd-theme
    versions:
    - 0.5.1
