language: "python"
before_install: "pip install -U pip pipenv"
install:
  - "pipenv install --dev"
before_script:
  - "pipenv run pipenv_to_requirements -f -o ci-requirements.txt"
script:
  - "if ! diff requirements.txt .travis.yml > /dev/null; then echo "The requirements.txt file is not up to date. Read contributing docs."; fi"
