version: 2

jobs:
  test:
    docker:
      - image: "circleci/python:3.8"
    working_directory: "~/repo"
    steps:
      - checkout
      - run:
          name: "Installing dependencies"
          command: "pip install -r requirements.txt"
      - run:
          name: "Running tests"
          command: "make test"

  linkcheck:
    docker:
      - image: "circleci/python:3.8"
    working_directory: "~/repo"
    steps:
      - checkout
      - run:
          name: "Installing dependencies"
          command: "pip install -r requirements.txt"
      - run:
          name: "Checking external links"
          command: "pipenv run linkcheck"

  # NOW_TOKEN needs to be set in CircleCI project settings
  deploy:
    docker:
      - image: "circleci/python:3.8-node"
    working_directory: "~/repo"
    steps:
      - checkout
      - run:
          name: "Installing now.sh"
          command: "sudo npm install --global --unsafe-perm now"
      - run:
          name: "Building & Deploying cojeapi.cz"
          command: |
            make build-cs
            now ./_build --name=cojeapi-docs-cs --prod --token=$NOW_TOKEN
      - run:
          name: "Building & Deploying whatisapi.org"
          command: |
            make build-en
            now ./_build --name=cojeapi-docs-en --prod --token=$NOW_TOKEN
      - run:
          name: "Deploying Server"
          command: "now ./code/server/16_deploy --name=cojeapi --token=$NOW_TOKEN"

workflows:
  version: 2
  build:
    jobs:
      - test
      - linkcheck
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
