version: 2.1

common:
  install: &install
    run: |
      python -m venv ./venv
      ./venv/bin/pip install -r requirements.txt

jobs:
  test-linux:
    docker:
      - image: "circleci/python:3.8"
    working_directory: "~/repo"
    steps:
      - checkout
      - *install
      - run: |
          source ./venv/bin/activate
          make test

  linkcheck:
    docker:
      - image: "circleci/python:3.8"
    working_directory: "~/repo"
    steps:
      - checkout
      - *install
      - run: |
          source ./venv/bin/activate
          make linkcheck

  # NOW_TOKEN needs to be set in CircleCI project settings
  deploy:
    docker:
      - image: "circleci/python:3.8-node"
    working_directory: "~/repo"
    steps:
      - checkout
      - *install
      - run:
          name: "Installing now.sh"
          command: "sudo npm install --global --unsafe-perm now"
      - run:
          name: "Building & Deploying cojeapi.cz"
          command: |
            source ./venv/bin/activate
            make build-cs
            now ./_build --name=cojeapi-docs-cs --prod --token=$NOW_TOKEN
      - run:
          name: "Building & Deploying whatisapi.org"
          command: |
            source ./venv/bin/activate
            make build-en
            now ./_build --name=cojeapi-docs-en --prod --token=$NOW_TOKEN
      - run:
          name: "Deploying Server"
          command: "now ./code/server/16_deploy --name=cojeapi --token=$NOW_TOKEN"

workflows:
  version: 2
  build:
    jobs:
      - test-linux
      - linkcheck
      - deploy:
          requires:
            - test-linux
          filters:
            branches:
              only: master
